[package]
name = "weather_app"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
public-ip = "0.2.2"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
ipgeolocate = "0.3.5"